application: Hello World Redstone
version: 1
deploy: true
pub: true
dart2js: true 
framework: redstone.dart

handlers:
- url: /hello
  script: server.dart

# Static content, will be served by your app's Nginx instance 
- url: /
  match: postregex
  static_dir: web


# Equivalent longer config for the Dart handler above  
#- url: /hello
#  script: hello_world.dart
#  handler: HelloWorld

